---
Name: paypalroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'paypalexpresscheckoutpayment_handler//$Action/$ID/$OtherID/$Version' : 'PayPalExpressCheckoutPayment_Handler'
