---
Name: paypalroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    paypalexpresscheckoutpaymenthandler//$Action/$ID/$OtherID/$Version: Sunnysideup\PaymentPaypal\PayPalExpressCheckoutPaymentHandler
