---
Name: paypalroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    paypalexpresscheckoutpayment_handler//$Action/$ID/$OtherID/$Version: Sunnysideup\PaymentPayPal\PayPalExpressCheckoutPayment_Handler
